### ISSUE TITLE
Stuck at the upgrade task.

### ISSUE THREAD

**Issue by neidiom** [systemli/ansible-role-roundcube#29]
My playbook gets stuck at the upgrade task.

```
TASK [systemli.roundcube : Run roundcube upgrade script] **********************************************************************************************************************************************************
```

If I run the script manually it expects user input and waits.

```
What version are you upgrading from? Type '?' if you don't know.
```

When I set `testing: False` the upgrade task is NOT skipped there fore this role is broken.

**Comment by doobry-systemli** [comment]
Hey @neidiom. Interesting, for us this task always succeeded in the past. But I see that it can get stuck due to the required user input. Would have to further investigate when it expects user input and when not :thinking:

> When I set ```testing: False``` the upgrade task is NOT skipped there fore this role is broken.

Setting `testing: True` (e.g. via `ansible-playbook [...] -e 'testing=true'`) should result in the task being skipped.

**Comment by t2d** [comment]
I could imagine that this is due to the fact, that you don't have a working setup before this. As stated in #31, this role was built around a working setup and we did many upgrades with it since then. Maybe we would need to handle a initial setup differently (not running upgrade script at all)

**Comment by t2d** [comment]
If you set `roundcube_enable_installer: true`, the upgrade task won't be run eb4b839a137a5389ae3bd3d5199640d583d86782
